name: "Notification Test" 

on:
  push:
    branches: [main]
  workflow_dispatch: 
  
jobs:
  get-alerts:
    name: GetAlerts
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
      repository-projects: write
      
      
    steps:
       - name: Call custom secret scanning action"
         uses: advanced-security-demo/secret-scanning-custom-notifications@main
         with:
           frequency: 6
           level: repo 
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
